databases:
  - name: Cherubim
    databaseName: cherubim_development
    user: cherubim_development

services:
  - type: web
    name: Cherubim
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cherubim_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false